version: "3.7"
services:
  canids-v2-ingestion:
    build:
      context: .
      dockerfile: ./ingestion/Dockerfile
    image: mcmaster-circ/canids-v2-ingestion
    container_name: canids-v2-ingestion
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
    environment:
      - flags= # Change this to specify additional flags (eg. --insecure)
      - asset=testdata2 # Change this to specify your asset name
      - hostname=host.docker.internal:50000 # Change this to specify the address of the backend
    secrets:
      - canids_ca_cert
    volumes:
      - ./ingestion/logs:/logs # Change this to specify the location of your logs
      - ingestiondb:/db

secrets:
  canids_ca_cert:
    file: ./ingestion/cert
volumes:
  ingestiondb:
