FROM zeek/zeek:6.0
RUN apt -y update && apt -y install cron iproute2
COPY ./ingestion/config/zeekctl.cfg /usr/locla/bin/etc/zeekctl.cfg
COPY --chmod=644 ./ingestion/config/zeek-crontab /etc/cron.d/zeek
ENV flags=--verbose


#TODO: How to point to backend on host network?
# COPY --from=build /usr/share/zoneinfo /usr/share/zoneinfo
# COPY --from=build /etc/passwd /etc/passwd
CMD ["sh", "-c", "service cron start ; zeekctl cron enable ; zeekctl deploy ; tail -f /dev/null"]